// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package sqlcgen

import (
	"context"
)

const getMilestone = `-- name: GetMilestone :one
SELECT id, plan_id, user_id, title, order_index, status, created_at, updated_at, deleted_at, server_rev FROM milestones
WHERE id = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type GetMilestoneParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetMilestone(ctx context.Context, arg GetMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, getMilestone, arg.ID, arg.UserID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.Title,
		&i.OrderIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
	)
	return i, err
}

const getMilestoneIncludingDeleted = `-- name: GetMilestoneIncludingDeleted :one
SELECT id, plan_id, user_id, title, order_index, status, created_at, updated_at, deleted_at, server_rev FROM milestones
WHERE id = ?1 AND user_id = ?2
`

type GetMilestoneIncludingDeletedParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetMilestoneIncludingDeleted(ctx context.Context, arg GetMilestoneIncludingDeletedParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, getMilestoneIncludingDeleted, arg.ID, arg.UserID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.Title,
		&i.OrderIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
	)
	return i, err
}

const insertMilestone = `-- name: InsertMilestone :exec
INSERT INTO milestones (id, plan_id, user_id, title, order_index, status, created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, NULL, ?9)
`

type InsertMilestoneParams struct {
	ID         string
	PlanID     string
	UserID     string
	Title      string
	OrderIndex int64
	Status     string
	CreatedAt  string
	UpdatedAt  string
	ServerRev  int64
}

func (q *Queries) InsertMilestone(ctx context.Context, arg InsertMilestoneParams) error {
	_, err := q.db.ExecContext(ctx, insertMilestone,
		arg.ID,
		arg.PlanID,
		arg.UserID,
		arg.Title,
		arg.OrderIndex,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ServerRev,
	)
	return err
}

const listMilestonesByPlan = `-- name: ListMilestonesByPlan :many
SELECT id, plan_id, user_id, title, order_index, status, created_at, updated_at, deleted_at, server_rev FROM milestones
WHERE plan_id = ?1 AND user_id = ?2 AND deleted_at IS NULL
ORDER BY order_index, created_at
`

type ListMilestonesByPlanParams struct {
	PlanID string
	UserID string
}

func (q *Queries) ListMilestonesByPlan(ctx context.Context, arg ListMilestonesByPlanParams) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestonesByPlan, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Milestone
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UserID,
			&i.Title,
			&i.OrderIndex,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestonesChangedSince = `-- name: ListMilestonesChangedSince :many
SELECT id, plan_id, user_id, title, order_index, status, created_at, updated_at, deleted_at, server_rev FROM milestones
WHERE user_id = ?1 AND server_rev > ?2
ORDER BY server_rev
`

type ListMilestonesChangedSinceParams struct {
	UserID string
	Cursor int64
}

func (q *Queries) ListMilestonesChangedSince(ctx context.Context, arg ListMilestonesChangedSinceParams) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestonesChangedSince, arg.UserID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Milestone
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UserID,
			&i.Title,
			&i.OrderIndex,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMilestone = `-- name: SoftDeleteMilestone :execrows
UPDATE milestones
SET deleted_at = ?1, updated_at = ?1, server_rev = ?2
WHERE id = ?3 AND user_id = ?4 AND deleted_at IS NULL
`

type SoftDeleteMilestoneParams struct {
	Now       *string
	ServerRev int64
	ID        string
	UserID    string
}

func (q *Queries) SoftDeleteMilestone(ctx context.Context, arg SoftDeleteMilestoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteMilestone,
		arg.Now,
		arg.ServerRev,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteMilestonesByPlan = `-- name: SoftDeleteMilestonesByPlan :exec
UPDATE milestones
SET deleted_at = ?1, updated_at = ?1, server_rev = ?2
WHERE plan_id = ?3 AND user_id = ?4 AND deleted_at IS NULL
`

type SoftDeleteMilestonesByPlanParams struct {
	Now       *string
	ServerRev int64
	PlanID    string
	UserID    string
}

func (q *Queries) SoftDeleteMilestonesByPlan(ctx context.Context, arg SoftDeleteMilestonesByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteMilestonesByPlan,
		arg.Now,
		arg.ServerRev,
		arg.PlanID,
		arg.UserID,
	)
	return err
}

const updateMilestone = `-- name: UpdateMilestone :exec
UPDATE milestones
SET title = ?1, order_index = ?2, status = ?3,
    updated_at = ?4, server_rev = ?5
WHERE id = ?6 AND user_id = ?7
`

type UpdateMilestoneParams struct {
	Title      string
	OrderIndex int64
	Status     string
	UpdatedAt  string
	ServerRev  int64
	ID         string
	UserID     string
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) error {
	_, err := q.db.ExecContext(ctx, updateMilestone,
		arg.Title,
		arg.OrderIndex,
		arg.Status,
		arg.UpdatedAt,
		arg.ServerRev,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertMilestoneLWW = `-- name: UpsertMilestoneLWW :execrows
INSERT INTO milestones (id, plan_id, user_id, title, order_index, status, created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
ON CONFLICT (id) DO UPDATE SET
    plan_id = excluded.plan_id,
    title = excluded.title,
    order_index = excluded.order_index,
    status = excluded.status,
    updated_at = excluded.updated_at,
    deleted_at = excluded.deleted_at,
    server_rev = excluded.server_rev
WHERE excluded.updated_at > milestones.updated_at
  AND milestones.user_id = excluded.user_id
`

type UpsertMilestoneLWWParams struct {
	ID         string
	PlanID     string
	UserID     string
	Title      string
	OrderIndex int64
	Status     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
	ServerRev  int64
}

func (q *Queries) UpsertMilestoneLWW(ctx context.Context, arg UpsertMilestoneLWWParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMilestoneLWW,
		arg.ID,
		arg.PlanID,
		arg.UserID,
		arg.Title,
		arg.OrderIndex,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ServerRev,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
