// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type LearningPlan struct {
	ID          string
	UserID      string
	Title       string
	Description string
	TargetDate  *string
	Status      string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   *string
	ServerRev   int64
}

type Milestone struct {
	ID         string
	PlanID     string
	UserID     string
	Title      string
	OrderIndex int64
	Status     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
	ServerRev  int64
}

type Recurrence struct {
	ID               string
	UserID           string
	Title            string
	Notes            string
	Frequency        string
	RepeatInterval   int64
	Weekdays         int64
	MonthDay         *int64
	StartTime        *string
	EndTime          *string
	EstimatedMinutes *int64
	ReminderMinutes  *int64
	StartDate        string
	EndDate          *string
	Status           string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
	ServerRev        int64
}

type SyncState struct {
	ID  int64
	Rev int64
}

type Task struct {
	ID               string
	UserID           string
	MilestoneID      *string
	Title            string
	Notes            string
	ScheduledDate    *string
	EstimatedMinutes *int64
	Status           string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
	ServerRev        int64
	RecurrenceID     *string
	StartTime        *string
	EndTime          *string
	ReminderMinutes  *int64
	CompletedAt      *string
}

type User struct {
	ID             string
	Email          string
	HashedPassword string
	CreatedAt      string
}
