// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlcgen

import (
	"context"
)

const getPlan = `-- name: GetPlan :one
SELECT id, user_id, title, description, target_date, status, created_at, updated_at, deleted_at, server_rev FROM learning_plans
WHERE id = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type GetPlanParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (LearningPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, arg.ID, arg.UserID)
	var i LearningPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TargetDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
	)
	return i, err
}

const getPlanIncludingDeleted = `-- name: GetPlanIncludingDeleted :one
SELECT id, user_id, title, description, target_date, status, created_at, updated_at, deleted_at, server_rev FROM learning_plans
WHERE id = ?1 AND user_id = ?2
`

type GetPlanIncludingDeletedParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetPlanIncludingDeleted(ctx context.Context, arg GetPlanIncludingDeletedParams) (LearningPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlanIncludingDeleted, arg.ID, arg.UserID)
	var i LearningPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TargetDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO learning_plans (id, user_id, title, description, target_date, status, created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, NULL, ?9)
`

type InsertPlanParams struct {
	ID          string
	UserID      string
	Title       string
	Description string
	TargetDate  *string
	Status      string
	CreatedAt   string
	UpdatedAt   string
	ServerRev   int64
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.ExecContext(ctx, insertPlan,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.TargetDate,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ServerRev,
	)
	return err
}

const listPlans = `-- name: ListPlans :many
SELECT id, user_id, title, description, target_date, status, created_at, updated_at, deleted_at, server_rev FROM learning_plans
WHERE user_id = ?1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPlans(ctx context.Context, userID string) ([]LearningPlan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningPlan
	for rows.Next() {
		var i LearningPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.TargetDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansChangedSince = `-- name: ListPlansChangedSince :many
SELECT id, user_id, title, description, target_date, status, created_at, updated_at, deleted_at, server_rev FROM learning_plans
WHERE user_id = ?1 AND server_rev > ?2
ORDER BY server_rev
`

type ListPlansChangedSinceParams struct {
	UserID string
	Cursor int64
}

func (q *Queries) ListPlansChangedSince(ctx context.Context, arg ListPlansChangedSinceParams) ([]LearningPlan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansChangedSince, arg.UserID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningPlan
	for rows.Next() {
		var i LearningPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.TargetDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlan = `-- name: SoftDeletePlan :execrows
UPDATE learning_plans
SET deleted_at = ?1, updated_at = ?1, server_rev = ?2
WHERE id = ?3 AND user_id = ?4 AND deleted_at IS NULL
`

type SoftDeletePlanParams struct {
	Now       *string
	ServerRev int64
	ID        string
	UserID    string
}

func (q *Queries) SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeletePlan,
		arg.Now,
		arg.ServerRev,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE learning_plans
SET title = ?1, description = ?2, target_date = ?3, status = ?4,
    updated_at = ?5, server_rev = ?6
WHERE id = ?7 AND user_id = ?8
`

type UpdatePlanParams struct {
	Title       string
	Description string
	TargetDate  *string
	Status      string
	UpdatedAt   string
	ServerRev   int64
	ID          string
	UserID      string
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.Title,
		arg.Description,
		arg.TargetDate,
		arg.Status,
		arg.UpdatedAt,
		arg.ServerRev,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertPlanLWW = `-- name: UpsertPlanLWW :execrows
INSERT INTO learning_plans (id, user_id, title, description, target_date, status, created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
ON CONFLICT (id) DO UPDATE SET
    title = excluded.title,
    description = excluded.description,
    target_date = excluded.target_date,
    status = excluded.status,
    updated_at = excluded.updated_at,
    deleted_at = excluded.deleted_at,
    server_rev = excluded.server_rev
WHERE excluded.updated_at > learning_plans.updated_at
  AND learning_plans.user_id = excluded.user_id
`

type UpsertPlanLWWParams struct {
	ID          string
	UserID      string
	Title       string
	Description string
	TargetDate  *string
	Status      string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   *string
	ServerRev   int64
}

func (q *Queries) UpsertPlanLWW(ctx context.Context, arg UpsertPlanLWWParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertPlanLWW,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.TargetDate,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ServerRev,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
