// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrences.sql

package sqlcgen

import (
	"context"
)

const getRecurrenceIncludingDeleted = `-- name: GetRecurrenceIncludingDeleted :one
SELECT id, user_id, title, notes, frequency, repeat_interval, weekdays, month_day, start_time, end_time, estimated_minutes, reminder_minutes, start_date, end_date, status, created_at, updated_at, deleted_at, server_rev FROM recurrences
WHERE id = ?1 AND user_id = ?2
`

type GetRecurrenceIncludingDeletedParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetRecurrenceIncludingDeleted(ctx context.Context, arg GetRecurrenceIncludingDeletedParams) (Recurrence, error) {
	row := q.db.QueryRowContext(ctx, getRecurrenceIncludingDeleted, arg.ID, arg.UserID)
	var i Recurrence
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Notes,
		&i.Frequency,
		&i.RepeatInterval,
		&i.Weekdays,
		&i.MonthDay,
		&i.StartTime,
		&i.EndTime,
		&i.EstimatedMinutes,
		&i.ReminderMinutes,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
	)
	return i, err
}

const listRecurrences = `-- name: ListRecurrences :many
SELECT id, user_id, title, notes, frequency, repeat_interval, weekdays, month_day, start_time, end_time, estimated_minutes, reminder_minutes, start_date, end_date, status, created_at, updated_at, deleted_at, server_rev FROM recurrences
WHERE user_id = ?1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListRecurrences(ctx context.Context, userID string) ([]Recurrence, error) {
	rows, err := q.db.QueryContext(ctx, listRecurrences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recurrence
	for rows.Next() {
		var i Recurrence
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Notes,
			&i.Frequency,
			&i.RepeatInterval,
			&i.Weekdays,
			&i.MonthDay,
			&i.StartTime,
			&i.EndTime,
			&i.EstimatedMinutes,
			&i.ReminderMinutes,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurrencesChangedSince = `-- name: ListRecurrencesChangedSince :many
SELECT id, user_id, title, notes, frequency, repeat_interval, weekdays, month_day, start_time, end_time, estimated_minutes, reminder_minutes, start_date, end_date, status, created_at, updated_at, deleted_at, server_rev FROM recurrences
WHERE user_id = ?1 AND server_rev > ?2
ORDER BY server_rev
`

type ListRecurrencesChangedSinceParams struct {
	UserID string
	Cursor int64
}

func (q *Queries) ListRecurrencesChangedSince(ctx context.Context, arg ListRecurrencesChangedSinceParams) ([]Recurrence, error) {
	rows, err := q.db.QueryContext(ctx, listRecurrencesChangedSince, arg.UserID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recurrence
	for rows.Next() {
		var i Recurrence
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Notes,
			&i.Frequency,
			&i.RepeatInterval,
			&i.Weekdays,
			&i.MonthDay,
			&i.StartTime,
			&i.EndTime,
			&i.EstimatedMinutes,
			&i.ReminderMinutes,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecurrenceLWW = `-- name: UpsertRecurrenceLWW :execrows
INSERT INTO recurrences (id, user_id, title, notes, frequency, repeat_interval, weekdays, month_day, start_time, end_time,
                         estimated_minutes, reminder_minutes, start_date, end_date, status,
                         created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10,
        ?11, ?12, ?13, ?14, ?15,
        ?16, ?17, ?18, ?19)
ON CONFLICT (id) DO UPDATE SET
    title = excluded.title,
    notes = excluded.notes,
    frequency = excluded.frequency,
    repeat_interval = excluded.repeat_interval,
    weekdays = excluded.weekdays,
    month_day = excluded.month_day,
    start_time = excluded.start_time,
    end_time = excluded.end_time,
    estimated_minutes = excluded.estimated_minutes,
    reminder_minutes = excluded.reminder_minutes,
    start_date = excluded.start_date,
    end_date = excluded.end_date,
    status = excluded.status,
    updated_at = excluded.updated_at,
    deleted_at = excluded.deleted_at,
    server_rev = excluded.server_rev
WHERE excluded.updated_at > recurrences.updated_at
  AND recurrences.user_id = excluded.user_id
`

type UpsertRecurrenceLWWParams struct {
	ID               string
	UserID           string
	Title            string
	Notes            string
	Frequency        string
	RepeatInterval   int64
	Weekdays         int64
	MonthDay         *int64
	StartTime        *string
	EndTime          *string
	EstimatedMinutes *int64
	ReminderMinutes  *int64
	StartDate        string
	EndDate          *string
	Status           string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
	ServerRev        int64
}

func (q *Queries) UpsertRecurrenceLWW(ctx context.Context, arg UpsertRecurrenceLWWParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertRecurrenceLWW,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Notes,
		arg.Frequency,
		arg.RepeatInterval,
		arg.Weekdays,
		arg.MonthDay,
		arg.StartTime,
		arg.EndTime,
		arg.EstimatedMinutes,
		arg.ReminderMinutes,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ServerRev,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
