// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, created_at, last_used_at)
VALUES (?1, ?2, ?3, ?3)
`

type CreateSessionParams struct {
	ID     string
	UserID string
	Now    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.Now)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, created_at, last_used_at, revoked_at FROM sessions
WHERE id = ?1 AND user_id = ?2 AND revoked_at IS NULL
`

type GetActiveSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = ?1
WHERE id = ?2 AND user_id = ?3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Now    *string
	ID     string
	UserID string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSession, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = ?1 WHERE id = ?2
`

type TouchSessionParams struct {
	Now string
	ID  string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.Now, arg.ID)
	return err
}
