// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlcgen

import (
	"context"
)

const bumpRev = `-- name: BumpRev :one
UPDATE sync_state SET rev = rev + 1 WHERE id = 1 RETURNING rev
`

func (q *Queries) BumpRev(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpRev)
	var rev int64
	err := row.Scan(&rev)
	return rev, err
}

const currentRev = `-- name: CurrentRev :one
SELECT rev FROM sync_state WHERE id = 1
`

func (q *Queries) CurrentRev(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, currentRev)
	var rev int64
	err := row.Scan(&rev)
	return rev, err
}
