// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
)

const getTask = `-- name: GetTask :one
SELECT id, user_id, milestone_id, title, notes, scheduled_date, estimated_minutes, status, created_at, updated_at, deleted_at, server_rev, recurrence_id, start_time, end_time, reminder_minutes, completed_at FROM tasks
WHERE id = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type GetTaskParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MilestoneID,
		&i.Title,
		&i.Notes,
		&i.ScheduledDate,
		&i.EstimatedMinutes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
		&i.RecurrenceID,
		&i.StartTime,
		&i.EndTime,
		&i.ReminderMinutes,
		&i.CompletedAt,
	)
	return i, err
}

const getTaskIncludingDeleted = `-- name: GetTaskIncludingDeleted :one
SELECT id, user_id, milestone_id, title, notes, scheduled_date, estimated_minutes, status, created_at, updated_at, deleted_at, server_rev, recurrence_id, start_time, end_time, reminder_minutes, completed_at FROM tasks
WHERE id = ?1 AND user_id = ?2
`

type GetTaskIncludingDeletedParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTaskIncludingDeleted(ctx context.Context, arg GetTaskIncludingDeletedParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskIncludingDeleted, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MilestoneID,
		&i.Title,
		&i.Notes,
		&i.ScheduledDate,
		&i.EstimatedMinutes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerRev,
		&i.RecurrenceID,
		&i.StartTime,
		&i.EndTime,
		&i.ReminderMinutes,
		&i.CompletedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (id, user_id, milestone_id, recurrence_id, title, notes, scheduled_date, start_time, end_time,
                   estimated_minutes, reminder_minutes, status, completed_at, created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9,
        ?10, ?11, ?12, ?13, ?14, ?15, NULL, ?16)
`

type InsertTaskParams struct {
	ID               string
	UserID           string
	MilestoneID      *string
	RecurrenceID     *string
	Title            string
	Notes            string
	ScheduledDate    *string
	StartTime        *string
	EndTime          *string
	EstimatedMinutes *int64
	ReminderMinutes  *int64
	Status           string
	CompletedAt      *string
	CreatedAt        string
	UpdatedAt        string
	ServerRev        int64
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.UserID,
		arg.MilestoneID,
		arg.RecurrenceID,
		arg.Title,
		arg.Notes,
		arg.ScheduledDate,
		arg.StartTime,
		arg.EndTime,
		arg.EstimatedMinutes,
		arg.ReminderMinutes,
		arg.Status,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ServerRev,
	)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, milestone_id, title, notes, scheduled_date, estimated_minutes, status, created_at, updated_at, deleted_at, server_rev, recurrence_id, start_time, end_time, reminder_minutes, completed_at FROM tasks
WHERE user_id = ?1
  AND deleted_at IS NULL
  AND (?2 IS NULL OR scheduled_date = ?2)
  AND (?3 IS NULL OR status = ?3)
  AND (?4 IS NULL OR milestone_id = ?4)
  AND (NOT CAST(?5 AS BOOLEAN) OR milestone_id IS NULL)
ORDER BY scheduled_date IS NULL, scheduled_date, created_at
`

type ListTasksParams struct {
	UserID        string
	ScheduledDate interface{}
	Status        interface{}
	MilestoneID   interface{}
	AdhocOnly     bool
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.UserID,
		arg.ScheduledDate,
		arg.Status,
		arg.MilestoneID,
		arg.AdhocOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MilestoneID,
			&i.Title,
			&i.Notes,
			&i.ScheduledDate,
			&i.EstimatedMinutes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
			&i.RecurrenceID,
			&i.StartTime,
			&i.EndTime,
			&i.ReminderMinutes,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPlan = `-- name: ListTasksByPlan :many
SELECT t.id, t.user_id, t.milestone_id, t.title, t.notes, t.scheduled_date, t.estimated_minutes, t.status, t.created_at, t.updated_at, t.deleted_at, t.server_rev, t.recurrence_id, t.start_time, t.end_time, t.reminder_minutes, t.completed_at FROM tasks t
JOIN milestones m ON m.id = t.milestone_id
WHERE m.plan_id = ?1 AND t.user_id = ?2 AND t.deleted_at IS NULL
ORDER BY m.order_index, t.scheduled_date IS NULL, t.scheduled_date, t.created_at
`

type ListTasksByPlanParams struct {
	PlanID string
	UserID string
}

func (q *Queries) ListTasksByPlan(ctx context.Context, arg ListTasksByPlanParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByPlan, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MilestoneID,
			&i.Title,
			&i.Notes,
			&i.ScheduledDate,
			&i.EstimatedMinutes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
			&i.RecurrenceID,
			&i.StartTime,
			&i.EndTime,
			&i.ReminderMinutes,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksChangedSince = `-- name: ListTasksChangedSince :many
SELECT id, user_id, milestone_id, title, notes, scheduled_date, estimated_minutes, status, created_at, updated_at, deleted_at, server_rev, recurrence_id, start_time, end_time, reminder_minutes, completed_at FROM tasks
WHERE user_id = ?1 AND server_rev > ?2
ORDER BY server_rev
`

type ListTasksChangedSinceParams struct {
	UserID string
	Cursor int64
}

func (q *Queries) ListTasksChangedSince(ctx context.Context, arg ListTasksChangedSinceParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksChangedSince, arg.UserID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MilestoneID,
			&i.Title,
			&i.Notes,
			&i.ScheduledDate,
			&i.EstimatedMinutes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
			&i.RecurrenceID,
			&i.StartTime,
			&i.EndTime,
			&i.ReminderMinutes,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToday = `-- name: ListToday :many
SELECT
    t.id, t.user_id, t.milestone_id, t.title, t.notes, t.scheduled_date, t.estimated_minutes, t.status, t.created_at, t.updated_at, t.deleted_at, t.server_rev, t.recurrence_id, t.start_time, t.end_time, t.reminder_minutes, t.completed_at,
    CAST(t.status = 'pending' AND t.scheduled_date < ?1 AS BOOLEAN) AS overdue,
    m.title AS milestone_title,
    p.id    AS plan_id,
    p.title AS plan_title
FROM tasks t
LEFT JOIN milestones m ON m.id = t.milestone_id
LEFT JOIN learning_plans p ON p.id = m.plan_id
WHERE t.user_id = ?2
  AND t.deleted_at IS NULL
  AND t.scheduled_date IS NOT NULL
  AND (
        (t.status = 'pending' AND t.scheduled_date <= ?1)
     OR (t.status <> 'pending' AND t.scheduled_date = ?1)
  )
  -- Missed routine occurrences don't pile up as overdue.
  AND (t.recurrence_id IS NULL OR t.scheduled_date = ?1)
  AND (t.milestone_id IS NULL OR (m.deleted_at IS NULL AND p.deleted_at IS NULL AND p.status <> 'archived'))
ORDER BY
    t.status <> 'pending',
    overdue DESC,
    t.milestone_id IS NULL,
    t.scheduled_date,
    t.start_time IS NULL,
    t.start_time,
    p.title,
    m.order_index,
    t.created_at
`

type ListTodayParams struct {
	Day    *string
	UserID string
}

type ListTodayRow struct {
	ID               string
	UserID           string
	MilestoneID      *string
	Title            string
	Notes            string
	ScheduledDate    *string
	EstimatedMinutes *int64
	Status           string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
	ServerRev        int64
	RecurrenceID     *string
	StartTime        *string
	EndTime          *string
	ReminderMinutes  *int64
	CompletedAt      *string
	Overdue          bool
	MilestoneTitle   *string
	PlanID           *string
	PlanTitle        *string
}

// Today: pending tasks due on or before the day, plus tasks already
// completed or skipped on that day. Tasks in archived or deleted plans
// are hidden.
func (q *Queries) ListToday(ctx context.Context, arg ListTodayParams) ([]ListTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, listToday, arg.Day, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodayRow
	for rows.Next() {
		var i ListTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MilestoneID,
			&i.Title,
			&i.Notes,
			&i.ScheduledDate,
			&i.EstimatedMinutes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerRev,
			&i.RecurrenceID,
			&i.StartTime,
			&i.EndTime,
			&i.ReminderMinutes,
			&i.CompletedAt,
			&i.Overdue,
			&i.MilestoneTitle,
			&i.PlanID,
			&i.PlanTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :execrows
UPDATE tasks
SET deleted_at = ?1, updated_at = ?1, server_rev = ?2
WHERE id = ?3 AND user_id = ?4 AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	Now       *string
	ServerRev int64
	ID        string
	UserID    string
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTask,
		arg.Now,
		arg.ServerRev,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteTasksByMilestone = `-- name: SoftDeleteTasksByMilestone :exec
UPDATE tasks
SET deleted_at = ?1, updated_at = ?1, server_rev = ?2
WHERE milestone_id = ?3 AND user_id = ?4 AND deleted_at IS NULL
`

type SoftDeleteTasksByMilestoneParams struct {
	Now         *string
	ServerRev   int64
	MilestoneID *string
	UserID      string
}

func (q *Queries) SoftDeleteTasksByMilestone(ctx context.Context, arg SoftDeleteTasksByMilestoneParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTasksByMilestone,
		arg.Now,
		arg.ServerRev,
		arg.MilestoneID,
		arg.UserID,
	)
	return err
}

const softDeleteTasksByPlan = `-- name: SoftDeleteTasksByPlan :exec
UPDATE tasks
SET deleted_at = ?1, updated_at = ?1, server_rev = ?2
WHERE tasks.user_id = ?3 AND tasks.deleted_at IS NULL
  AND tasks.milestone_id IN (SELECT m.id FROM milestones m WHERE m.plan_id = ?4)
`

type SoftDeleteTasksByPlanParams struct {
	Now       *string
	ServerRev int64
	UserID    string
	PlanID    string
}

func (q *Queries) SoftDeleteTasksByPlan(ctx context.Context, arg SoftDeleteTasksByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTasksByPlan,
		arg.Now,
		arg.ServerRev,
		arg.UserID,
		arg.PlanID,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET milestone_id = ?1, title = ?2, notes = ?3, scheduled_date = ?4,
    start_time = ?5, end_time = ?6, estimated_minutes = ?7,
    reminder_minutes = ?8, status = ?9, completed_at = ?10,
    updated_at = ?11, server_rev = ?12
WHERE id = ?13 AND user_id = ?14
`

type UpdateTaskParams struct {
	MilestoneID      *string
	Title            string
	Notes            string
	ScheduledDate    *string
	StartTime        *string
	EndTime          *string
	EstimatedMinutes *int64
	ReminderMinutes  *int64
	Status           string
	CompletedAt      *string
	UpdatedAt        string
	ServerRev        int64
	ID               string
	UserID           string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.MilestoneID,
		arg.Title,
		arg.Notes,
		arg.ScheduledDate,
		arg.StartTime,
		arg.EndTime,
		arg.EstimatedMinutes,
		arg.ReminderMinutes,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ServerRev,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertTaskLWW = `-- name: UpsertTaskLWW :execrows
INSERT INTO tasks (id, user_id, milestone_id, recurrence_id, title, notes, scheduled_date, start_time, end_time,
                   estimated_minutes, reminder_minutes, status, completed_at, created_at, updated_at, deleted_at, server_rev)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9,
        ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17)
ON CONFLICT (id) DO UPDATE SET
    milestone_id = excluded.milestone_id,
    recurrence_id = excluded.recurrence_id,
    title = excluded.title,
    notes = excluded.notes,
    scheduled_date = excluded.scheduled_date,
    start_time = excluded.start_time,
    end_time = excluded.end_time,
    estimated_minutes = excluded.estimated_minutes,
    reminder_minutes = excluded.reminder_minutes,
    status = excluded.status,
    completed_at = excluded.completed_at,
    updated_at = excluded.updated_at,
    deleted_at = excluded.deleted_at,
    server_rev = excluded.server_rev
WHERE excluded.updated_at > tasks.updated_at
  AND tasks.user_id = excluded.user_id
`

type UpsertTaskLWWParams struct {
	ID               string
	UserID           string
	MilestoneID      *string
	RecurrenceID     *string
	Title            string
	Notes            string
	ScheduledDate    *string
	StartTime        *string
	EndTime          *string
	EstimatedMinutes *int64
	ReminderMinutes  *int64
	Status           string
	CompletedAt      *string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
	ServerRev        int64
}

func (q *Queries) UpsertTaskLWW(ctx context.Context, arg UpsertTaskLWWParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertTaskLWW,
		arg.ID,
		arg.UserID,
		arg.MilestoneID,
		arg.RecurrenceID,
		arg.Title,
		arg.Notes,
		arg.ScheduledDate,
		arg.StartTime,
		arg.EndTime,
		arg.EstimatedMinutes,
		arg.ReminderMinutes,
		arg.Status,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ServerRev,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
